/**
 * T124a — SC-001: a new member goes from sign-in to holding a generated
 * specification linked to its requirements in under 15 minutes, with no
 * external help.
 *
 * HONESTY NOTE (Constitution IX): this journey is a real measurement only
 * when executed against a running stack. Run it with:
 *
 *   1. docker compose up -d postgres          # or a local PostgreSQL 16
 *   2. pnpm --filter backend exec prisma migrate deploy
 *   3. pnpm --filter backend start            # API on :3000
 *   4. pnpm --filter frontend dev             # UI on :5173
 *   5. pnpm --filter e2e exec playwright test tests/sc-001-journey.spec.ts
 *
 * Until that command has been run and PASSED, SC-001 is "authored, not yet
 * measured" — never report it as satisfied on the strength of this file
 * existing.
 */
import { expect, test } from '@playwright/test';

const FIFTEEN_MINUTES_MS = 15 * 60 * 1000;
const BASE_URL = process.env.E2E_BASE_URL ?? 'http://localhost:5173';

test('SC-001 — sign-in to a generated, requirement-linked specification in under 15 minutes', async ({
  page,
}) => {
  const startedAt = Date.now();

  // 1. Sign in — the journey starts unauthenticated.
  await page.goto(BASE_URL);
  await page.getByLabel(/email/i).fill(process.env.E2E_EMAIL ?? 'member@example.com');
  await page.getByLabel(/password/i).fill(process.env.E2E_PASSWORD ?? 'correct horse battery');
  await page.getByRole('button', { name: /sign in/i }).click();
  await expect(page.getByRole('heading', { name: /projects/i })).toBeVisible();

  // 2. Create a project.
  await page.getByLabel(/project name/i).fill('SC-001 journey');
  await page.getByRole('button', { name: /create/i }).click();
  await page.getByRole('button', { name: 'SC-001 journey' }).click();

  // 3. Capture a requirement.
  await page.getByLabel(/requirement/i).fill('The system MUST let a member reset their password.');
  await page.getByRole('button', { name: /add requirement/i }).click();
  await expect(page.getByText(/MUST let a member reset/)).toBeVisible();

  // 4. Generate a specification and wait for the job to settle (FR-028: the
  //    UI stays usable while the job runs — polling, not blocking).
  await page.getByRole('button', { name: /generate specification/i }).click();
  await expect(page.getByText(/succeeded/i)).toBeVisible({ timeout: FIFTEEN_MINUTES_MS });

  // 5. Open the generated specification: engine provenance visible (FR-022).
  await page.getByRole('button', { name: /sc-001 journey/i }).click();
  await expect(page.getByText(/generated by/i)).toBeVisible();

  // 6. The specification is linked back to its requirements (FR-007).
  await expect(page.getByText(/MUST let a member reset/)).toBeVisible();

  // SC-001's number: the whole journey fits inside 15 minutes.
  expect(Date.now() - startedAt).toBeLessThan(FIFTEEN_MINUTES_MS);
});
