/**
 * T488 · Check `G-26-07` — regeneration on unchanged input is byte-identical.
 * Written to FAIL before T491 exists (Constitution V).
 *
 * **`SC-ESK-004` and `RF-2`.** The register is generated *and* committed, so it
 * is compared against a fresh generation on every CI run. Any value that varies
 * without the repository varying makes that comparison fail for a reason nobody
 * can act on — and the correct response to a check that cries wolf is to delete
 * the check, which would take the drift guarantee with it.
 *
 * `T478` asserts determinism of the **renderer** given fixed rows. This asserts
 * determinism of the whole pipeline — enumeration, derivation, ordering,
 * rendering — against the **real repository**, where filesystem order and
 * directory-read sequence are the things most likely to leak in.
 */
import { describe, expect, it } from 'vitest';
import { buildRegister, buildRegisterModel } from './build';

describe('G-26-07 · the pipeline is a function of the tree (SC-ESK-004)', () => {
  it('produces byte-identical output on consecutive runs', () => {
    // The whole assertion in one line. If this fails, the committed register
    // cannot be trusted to mean anything.
    expect(buildRegister()).toBe(buildRegister());
  });

  it('produces byte-identical output across many runs, not just two', () => {
    // Two runs would miss a value that alternates or depends on a cache warmed
    // by the first call.
    const first = buildRegister();
    for (let run = 0; run < 5; run += 1) {
      expect(buildRegister(), `run ${run + 2} differed from run 1`).toBe(first);
    }
  });

  it('orders rows identically every time, regardless of directory read order', () => {
    const order = () => buildRegisterModel().rows.map((row) => row.epic);
    expect(order()).toEqual(order());
    expect(order()).toEqual([...order()].sort());
  });

  it('orders findings identically every time', () => {
    // Findings are generated by iterating Epics and their evidence. Unordered
    // output here would produce a diff on every run while the tree stood still.
    const findings = () => buildRegisterModel().findings.map((f) => `${f.epic}:${f.finding}`);
    expect(findings()).toEqual(findings());
  });

  it('contains no value derived from the clock OUTSIDE the waivers section', () => {
    // DEF-026-003. `RF-5` requires every active waiver to show its expiry, and
    // an expiry is INPUT, not clock-derived — it changes only when a person
    // changes it, so it produces no spurious diff. The clock ban still applies
    // everywhere else, which is what `RF-2` was actually protecting.
    const text = buildRegister();
    const beforeWaivers = text.split('## Active waivers')[0] ?? text;
    expect(beforeWaivers).not.toMatch(/\d{4}-\d{2}-\d{2}/);
    expect(text).not.toMatch(/\b\d{2}:\d{2}\b/);
  });

  it('permits a declared expiry only inside the waivers section', () => {
    const text = buildRegister();
    const dates = [...text.matchAll(/\d{4}-\d{2}-\d{2}/g)];
    if (dates.length === 0) return;
    const waiverSection = text.indexOf('## Active waivers');
    expect(waiverSection, 'a date appears with no waivers section at all').toBeGreaterThan(-1);
    for (const date of dates) {
      expect(
        date.index ?? -1,
        `a date appears outside the waivers section: ${date[0]}`,
      ).toBeGreaterThan(waiverSection);
    }
  });

  it('contains no absolute path from this machine', () => {
    // A leaked absolute path is deterministic on one machine and different on
    // every other, which is the worst version of this failure: green locally,
    // red in CI, and the diff looks like somebody's home directory.
    const text = buildRegister();
    expect(text).not.toMatch(/[A-Za-z]:[\\/]/);
    expect(text).not.toContain('/home/');
    expect(text).not.toContain('/Users/');
  });
});
