/**
 * `T1483` (EPIC-042, `FR-EXT-020`–`FR-EXT-027`, `R-042-4`, `R-042-5`) — the
 * render is deterministic, its digest is meaningful, and an on-disk digest is
 * classified by one rule. Written to FAIL before `T1484`.
 */
import { createHash } from 'node:crypto';
import { governedExecutionSection } from '@pmi/workspace-bundle';
import { describe, expect, it } from 'vitest';
import { ConstitutionRenderService } from '../../../src/modules/governance/constitution-render.service.js';
import { InMemoryConstitutionRenderStore } from '../../../src/modules/governance/constitution-render.store.js';
import { InMemoryProjectConstraintStore } from '../../../src/modules/governance/project-constraint.store.js';
import { ProjectConstraintService } from '../../../src/modules/governance/project-constraint.service.js';
import { InMemoryDecompositionPolicyStore } from '../../../src/modules/governance/decomposition-policy.store.js';
import { DecompositionPolicyService } from '../../../src/modules/governance/decomposition-policy.service.js';

const NOW = new Date('2026-09-04T12:00:00Z');
const CTX = { workspaceId: 'ws_a', projectId: 'p_a', userId: 'u_owner' };

function harness(steering: { subject: string; scopeType: 'organization' | 'workspace' | 'project' | 'product'; content: string; id: string }[] = []) {
  const audit = { record: async (): Promise<void> => undefined };
  const constraints = new ProjectConstraintService({ store: new InMemoryProjectConstraintStore(), audit, now: () => NOW });
  const policy = new DecompositionPolicyService({ store: new InMemoryDecompositionPolicyStore(), audit });
  const renders = new InMemoryConstitutionRenderStore();
  const service = new ConstitutionRenderService({
    store: renders,
    constraints,
    policy,
    projects: { get: async () => ({ id: 'p_a', name: 'Alpha' }) },
    steering: { resolvedForProject: async () => steering.map((s) => ({ ...s, version: 1 })) },
    audit,
    now: () => NOW,
  });
  return { service, constraints, policy, renders };
}

function digestOf(content: string): string {
  const zeroed = content.replace(/digest [0-9a-f]{64}/, `digest ${'0'.repeat(64)}`);
  return createHash('sha256').update(zeroed, 'utf8').digest('hex');
}

describe('T1483 · the render', () => {
  it('has the section order of contracts/governance-api.md §4, \\n endings, one trailing newline', async () => {
    const { service } = harness();
    const r = await service.current(CTX);
    const headings = r.content.split('\n').filter((l) => l.startsWith('## '));
    expect(headings).toEqual(['## Core Principles', '## Constraints', '## Non-goals', '## Decomposition Policy', '## Governed Execution', '## Steering']);
    expect(r.content).not.toContain('\r');
    expect(r.content.endsWith('\n')).toBe(true);
    expect(r.content.endsWith('\n\n')).toBe(false);
    expect(r.content.startsWith('<!-- GENERATED by PMI Studio from project p_a · constitution version 1 · digest ')).toBe(true);
    expect(r.content).toContain('# Alpha Constitution');
  });

  it('keeps an empty section with its heading and _None recorded._', async () => {
    const { service } = harness();
    const r = await service.current(CTX);
    expect(r.content).toContain('## Non-goals\n\n_None recorded._\n');
  });

  it('renders active entries by kind in order and omits retired ones', async () => {
    const { service, constraints } = harness();
    await constraints.create(CTX, { kind: 'principle', title: 'Spec first', body: 'Write it down.' });
    const gone = await constraints.create(CTX, { kind: 'principle', title: 'Gone', body: 'Retired.' });
    await constraints.retire(CTX, gone.id);
    await constraints.create(CTX, { kind: 'constraint', title: 'Postgres 16', body: 'Nothing else.' });
    const r = await service.current(CTX);
    expect(r.content).toContain('## Core Principles\n\n### Spec first\n\nWrite it down.\n');
    expect(r.content).toContain('## Constraints\n\n### Postgres 16\n\nNothing else.\n');
    expect(r.content).not.toContain('Gone');
  });

  it('renders the Decomposition Policy from the stored policy and the Governed Execution section from the bundle, byte-identical', async () => {
    const { service, policy } = harness();
    await policy.put(CTX, { oneSpecPerEpic: true, taskCeiling: 40, splitRequiresConfirmation: true, offlineMode: 'provisional' });
    const r = await service.current(CTX);
    expect(r.content).toContain('- One specification per Epic.\n');
    expect(r.content).toContain('exceeds 40 MUST be split');
    expect(r.content).toContain('- Policy version 2.\n');
    expect(r.content).toContain(`## Governed Execution\n\n${governedExecutionSection('provisional')}`);
  });

  it('lists resolved steering broadest-first under Steering and nothing else', async () => {
    const { service } = harness([
      { id: 's2', subject: 'coding_standards', scopeType: 'project', content: 'Project rule.' },
      { id: 's1', subject: 'security', scopeType: 'organization', content: 'Org rule.' },
    ]);
    const r = await service.current(CTX);
    const steering = r.content.slice(r.content.indexOf('## Steering'));
    expect(steering.indexOf('### security')).toBeLessThan(steering.indexOf('### coding_standards'));
    expect(steering).toContain('Org rule.');
  });

  it('a constraint titled Governed Execution renders under its kind; the invariant section is untouched', async () => {
    const { service, constraints } = harness();
    await constraints.create(CTX, { kind: 'principle', title: 'Governed Execution', body: 'My own words.' });
    const r = await service.current(CTX);
    expect(r.content).toContain('## Core Principles\n\n### Governed Execution\n\nMy own words.\n');
    expect(r.content).toContain(`## Governed Execution\n\n${governedExecutionSection('strict')}`);
    expect(r.content.split('\n## Governed Execution\n').length).toBe(2);
  });
});

describe('T1483 · digest and records', () => {
  it('the digest is SHA-256 of the content with the header digest zeroed, and the header carries it', async () => {
    const { service } = harness();
    const r = await service.current(CTX);
    expect(r.digest).toMatch(/^[0-9a-f]{64}$/);
    expect(r.digest).toBe(digestOf(r.content));
    expect(r.content).toContain(`digest ${r.digest}`);
  });

  it('a re-read with unchanged inputs inserts no new row; a change inserts one with version + 1', async () => {
    const { service, constraints, renders } = harness();
    const first = await service.current(CTX);
    const again = await service.current(CTX);
    expect(again.version).toBe(first.version);
    expect(await renders.listForProject('p_a')).toHaveLength(1);
    await constraints.create(CTX, { kind: 'non_goal', title: 'No mobile', body: '' });
    const next = await service.current(CTX);
    expect(next.version).toBe(first.version + 1);
    expect(next.digest).not.toBe(first.digest);
    expect(await renders.listForProject('p_a')).toHaveLength(2);
  });

  it('records the inputs that produced the render', async () => {
    const { service, renders } = harness();
    await service.current(CTX);
    const [row] = await renders.listForProject('p_a');
    expect(row?.inputs).toMatchObject({ policyVersion: 1, constraintsMaxVersion: 0, steeringDocumentIds: [] });
  });
});

describe('T1483 · classify (data-model.md §3)', () => {
  it('current, stale, drift, missing', async () => {
    const { service, constraints } = harness();
    const first = await service.current(CTX);
    await constraints.create(CTX, { kind: 'principle', title: 'Later', body: '' });
    const second = await service.current(CTX);
    expect(await service.classify(CTX, second.digest)).toBe('current');
    expect(await service.classify(CTX, first.digest)).toBe('stale');
    expect(await service.classify(CTX, 'f'.repeat(64))).toBe('drift');
    expect(await service.classify(CTX, null)).toBe('missing');
  });

  it('classify never renders: a project with no render yet reports drift for any digest and missing for null', async () => {
    const { service, renders } = harness();
    expect(await service.classify(CTX, 'a'.repeat(64))).toBe('drift');
    expect(await service.classify(CTX, null)).toBe('missing');
    expect(await renders.listForProject('p_a')).toHaveLength(0);
  });
});
