/**
 * `T1517` (EPIC-042, US3, `FR-EXT-020`–`FR-EXT-024`, `SC-EXT-004`, `SC-EXT-009`)
 * — the render through the composed `AppModule`: two principles, a constraint,
 * a non-goal and a policy through the session routes; `GET …/constitution` in
 * the §4 order with the invariant section byte-equal to the bundle's; every
 * edit changes the digest; a re-read with no change inserts no render; the
 * Steering section carries the project's resolved steering documents.
 *
 * Mutation owed at closure (`SC-EXT-009`): take the Governed Execution text from
 * a constraint entry and observe the byte-equality assertion fail.
 * Written to FAIL before `T1518`.
 */
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { governedExecutionSection } from '@pmi/workspace-bundle';
import request from 'supertest';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { startAuthenticatedApp, type AuthenticatedApp } from '../helpers/authenticated-app.js';

const noRuntime = process.env['DOCKER_UNAVAILABLE'] === '1';
const suite = noRuntime ? describe.skip : describe;

let started: AuthenticatedApp;
let root: string;
let projectId = '';

beforeAll(async () => {
  if (noRuntime) return;
  root = mkdtempSync(join(tmpdir(), 'pmi-render-root-'));
  process.env['PMI_PROJECTS_ROOT'] = root;
  process.env['PMI_PROJECTS_ROOT_HOST'] = root;
  process.env['PMI_PUBLIC_URL'] = 'http://localhost:3000';
  started = await startAuthenticatedApp({ workspaceId: 'ws_render', userId: 'u_owner' });
  const api = started.app.getHttpServer();
  const a = await request(api).post('/v1/projects').set('Cookie', started.cookie).send({ name: 'Alpha', rootPath: 'alpha' }).expect(201);
  projectId = a.body.id;
}, 600_000);

afterAll(async () => {
  await started?.close();
  rmSync(root, { recursive: true, force: true });
  delete process.env['PMI_PROJECTS_ROOT'];
  delete process.env['PMI_PROJECTS_ROOT_HOST'];
  delete process.env['PMI_PUBLIC_URL'];
}, 120_000);

suite('T1517 · the render follows the owner', () => {
  it('entries and the policy render in order; the invariant section is byte-equal to the bundle; the digest changes on every edit; an unchanged read inserts nothing', async () => {
    const api = started.app.getHttpServer();
    const first = await request(api).get(`/v1/projects/${projectId}/constitution`).set('Cookie', started.cookie).expect(200);
    expect(first.body.version).toBe(1);
    expect(first.body.content).toContain('## Core Principles\n\n_None recorded._\n');

    const digests = new Set<string>([first.body.digest as string]);
    for (const entry of [
      { kind: 'principle', title: 'Spec first', body: 'Write it down.' },
      { kind: 'principle', title: 'Then build', body: 'Only then.' },
      { kind: 'constraint', title: 'Postgres 16', body: 'Nothing else.' },
      { kind: 'non_goal', title: 'No mobile', body: 'Not in v1.' },
    ]) {
      await request(api).post(`/v1/projects/${projectId}/constraints`).set('Cookie', started.cookie).send(entry).expect(201);
      const res = await request(api).get(`/v1/projects/${projectId}/constitution`).set('Cookie', started.cookie).expect(200);
      expect(digests.has(res.body.digest as string), 'every edit changes the digest').toBe(false);
      digests.add(res.body.digest as string);
    }
    await request(api).put(`/v1/projects/${projectId}/policy`).set('Cookie', started.cookie).send({ oneSpecPerEpic: true, taskCeiling: 30, splitRequiresConfirmation: true, offlineMode: 'provisional' }).expect(200);

    const res = await request(api).get(`/v1/projects/${projectId}/constitution`).set('Cookie', started.cookie).expect(200);
    const content = res.body.content as string;
    const headings = content.split('\n').filter((l) => l.startsWith('## '));
    expect(headings).toEqual(['## Core Principles', '## Constraints', '## Non-goals', '## Decomposition Policy', '## Governed Execution', '## Steering']);
    expect(content).toContain('## Core Principles\n\n### Spec first\n\nWrite it down.\n\n### Then build\n\nOnly then.\n');
    expect(content).toContain('## Constraints\n\n### Postgres 16\n\nNothing else.\n');
    expect(content).toContain('## Non-goals\n\n### No mobile\n\nNot in v1.\n');
    expect(content).toContain('exceeds 30 MUST be split');
    // SC-EXT-009: the invariant section, byte-equal to the bundle's for this offline mode.
    expect(content).toContain(`## Governed Execution\n\n${governedExecutionSection('provisional')}`);
    expect(content.startsWith(`<!-- GENERATED by PMI Studio from project ${projectId} · constitution version ${res.body.version} · digest ${res.body.digest}`)).toBe(true);

    // An unchanged read repeats the same version and digest — no new render row.
    const again = await request(api).get(`/v1/projects/${projectId}/constitution`).set('Cookie', started.cookie).expect(200);
    expect(again.body.version).toBe(res.body.version);
    expect(again.body.digest).toBe(res.body.digest);
    // Versions grew once per change: initial + 4 entries + 1 policy.
    expect(res.body.version).toBe(6);
  });

  it('the Steering section carries the project\'s resolved steering documents, broadest first, and nothing else', async () => {
    const api = started.app.getHttpServer();
    // EPIC-019 steering: an organization-scope document and a project-scope one, distinct subjects.
    const org = await request(api).post('/v1/steering').set('Cookie', started.cookie).send({ subject: 'security', scopeType: 'organization', scopeRef: 'org_default', content: 'Org: least privilege.' });
    const proj = await request(api).post('/v1/steering').set('Cookie', started.cookie).send({ subject: 'coding_standards', scopeType: 'project', scopeRef: projectId, content: 'Project: strict TypeScript.' });
    expect([201, 200]).toContain(org.status);
    expect([201, 200]).toContain(proj.status);
    const res = await request(api).get(`/v1/projects/${projectId}/constitution`).set('Cookie', started.cookie).expect(200);
    const steering = (res.body.content as string).slice((res.body.content as string).indexOf('## Steering'));
    expect(steering).toContain('### security\n\nOrg: least privilege.\n');
    expect(steering).toContain('### coding_standards\n\nProject: strict TypeScript.\n');
    expect(steering.indexOf('### security')).toBeLessThan(steering.indexOf('### coding_standards'));
    expect(steering).not.toContain('_None recorded._');
  });
});
