/**
 * T792 — the Decision Inbox transcript conforms. Constitution XI Tier 2.
 *
 * Asserts `docs/uat/EPIC-031-inbox-transcript.md` **exists**, **names the run**
 * — the harness that generated it and the stack it ran against — and was
 * **generated rather than authored**: it carries the harness's own header and
 * timestamped steps, and no credential.
 *
 * **Known-red until `T791` is run** (`governance/known-red.json`). The run needs
 * the reference-local stack and a seeded user's password, which an agent does
 * not hold; typing the transcript instead would fabricate exactly the evidence
 * this check exists to test for. The planted cases below prove it can tell a
 * conforming transcript from a hand-written one, so it is not decoration while
 * it waits.
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const TRANSCRIPT = resolve(here, '../../../docs/uat/EPIC-031-inbox-transcript.md');

export function transcriptFindings(text: string): string[] {
  const findings: string[] = [];
  if (!/^# EPIC-031 — Decision Inbox transcript \(Constitution XI Tier 2\)/m.test(text)) findings.push('no harness header');
  if (!/\*\*Generated by\*\* `e2e\/tests\/epic-031-inbox\.spec\.ts` on \d{4}-\d{2}-\d{2}T/.test(text)) {
    findings.push('does not name the harness and the time it ran');
  }
  if (!/\*\*Stack\*\*: \S/.test(text)) findings.push('does not name the stack');
  const steps = text.match(/^- \d{4}-\d{2}-\d{2}T[\d:.]+Z /gm) ?? [];
  if (steps.length < 6) findings.push(`has ${steps.length} timestamped steps; the journey has at least six`);
  for (const must of [/one action/i, /FR-DPE-025/, /keyboard/i, /left the Inbox/i]) {
    if (!must.test(text)) findings.push(`never records ${must.source}`);
  }
  if (/password\s*[:=]\s*\S+/i.test(text) || /pmi_ct_[A-Za-z0-9_-]{20,}/.test(text)) findings.push('carries a credential');
  return findings;
}

describe('T792 · the Decision Inbox transcript (XI Tier 2)', () => {
  it('exists — generated by running e2e/tests/epic-031-inbox.spec.ts against a stack', () => {
    expect(existsSync(TRANSCRIPT), `no transcript at ${TRANSCRIPT}; T791 has not been run`).toBe(true);
  });

  it('names the run and was generated rather than authored', () => {
    expect(transcriptFindings(readFileSync(TRANSCRIPT, 'utf8'))).toEqual([]);
  });
});

describe('T792 · the check can tell generated from authored', () => {
  const generated = [
    '# EPIC-031 — Decision Inbox transcript (Constitution XI Tier 2)',
    '',
    '**Generated by** `e2e/tests/epic-031-inbox.spec.ts` on 2026-10-08T12:00:00.000Z · **Stack**: reference local',
    '',
    '- 2026-10-08T12:00:00.000Z Signed in.',
    '- 2026-10-08T12:00:01.000Z Requested release.promote: pending.',
    '- 2026-10-08T12:00:02.000Z Reached the Decision Inbox in one action from Home.',
    '- 2026-10-08T12:00:03.000Z The entry names what blocks it (FR-DPE-025).',
    '- 2026-10-08T12:00:04.000Z Approved by keyboard; the item left the Inbox.',
    '- 2026-10-08T12:00:05.000Z The pending decision is resolved.',
  ].join('\n');

  it('passes a planted generated transcript', () => {
    expect(transcriptFindings(generated)).toEqual([]);
  });

  it.each([
    ['a hand-written summary', '# Inbox UAT\n\nEverything worked. Approved fine.'],
    ['a transcript naming no stack', generated.replace(/\*\*Stack\*\*: reference local/, '')],
    ['a transcript with too few steps', generated.split('\n').slice(0, 6).join('\n')],
    ['a transcript carrying a password', `${generated}\n- 2026-10-08T12:00:06.000Z password: hunter2`],
  ])('flags %s', (_label, text) => {
    expect(transcriptFindings(text).length).toBeGreaterThan(0);
  });
});
