/**
 * `T1992` (EPIC-047) — the Tier 2 transcript of the Engineering Experts journey.
 *
 * Constitution XI Tier 2: a journey is delivered (the `/experts` screen), so a
 * transcript **generated by a run against a running application** must exist
 * before closure. This check is red until it does, and is declared in
 * `governance/known-red.json` rather than silenced.
 *
 * It cannot be produced here, and typing one would be the fabrication this
 * check exists to catch: registering and approving an Expert work (Phase 9), and
 * a dispatch is registered with `EPIC-037` under the Expert's own identity
 * (`DEF-047-001`), but **no run executes to show** because no agent runtime is
 * composed into the API (`DEF-047-002`).
 */
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

const here = dirname(fileURLToPath(import.meta.url));
const TRANSCRIPT = resolve(here, '..', '..', '..', 'specs', '047-engineering-experts', 'tier2-transcript.md');

/** Quickstart Q17 plus the steps that prove the screen shows real records. */
const STEPS = ['open /experts', 'open an expert', 'compare versions', 'open a run', 'delegation tree', '360px'];

describe('T1992 · the Tier 2 Engineering Experts transcript exists and is generated', () => {
  it('specs/047-engineering-experts/tier2-transcript.md is committed', () => {
    expect(existsSync(TRANSCRIPT), 'the Tier 2 transcript has not been produced by a run yet').toBe(true);
  });

  it('records every step of the journey', () => {
    const text = existsSync(TRANSCRIPT) ? readFileSync(TRANSCRIPT, 'utf8').toLowerCase() : '';
    for (const step of STEPS) expect(text, `the transcript does not record: ${step}`).toContain(step);
  });

  it('says it was generated by a run, naming the stack and the instant', () => {
    const text = existsSync(TRANSCRIPT) ? readFileSync(TRANSCRIPT, 'utf8') : '';
    expect(text).toMatch(/generated by/i);
    // An ISO-8601 instant: date, the separator, then the clock.
    expect(text).toMatch(/\d{4}-\d{2}-\d{2}.\d{2}:\d{2}/);
  });
});
