/**
 * T084 — the specification detail view (US3).
 *
 * FR-022: the generating engine and its version are provenance and always
 * shown. FR-032: out-of-date is a state a human acts on — flagged as a live
 * status region, never auto-corrected.
 */
import { useEffect, useState, type ReactElement } from 'react';
import { ApiError, type ApiClient, type Specification } from '../services/api';

export interface SpecificationViewProps {
  api: ApiClient;
  specificationId: string;
}

export function SpecificationView({ api, specificationId }: SpecificationViewProps): ReactElement {
  const [specification, setSpecification] = useState<Specification | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    void (async (): Promise<void> => {
      try {
        setSpecification(await api.getSpecification(specificationId));
      } catch (err) {
        setError(err instanceof ApiError ? err.message : 'Something went wrong. Please try again.');
      }
    })();
  }, [api, specificationId]);

  if (specification === null) {
    return <main>{error !== null ? <p role="alert">{error}</p> : <p>Loading…</p>}</main>;
  }

  // EPIC-020 T268 (SC-ENH-006): ONE live region for staleness. FR-032's
  // out-of-date flag and FR-ENH-006's currency status share it, so the two
  // can never disagree on screen — and no specification is silently stale.
  const stale = specification.isOutOfDate || specification.currencyStatus === 'stale';
  const staleDetail =
    specification.staleReason ?? 'its source requirements changed after generation';

  return (
    <main>
      <h1>{specification.title}</h1>
      {stale && (
        <p role="status">
          This specification is not current (out of date) — {staleDetail}. Nothing is regenerated
          automatically; reconcile it deliberately.
        </p>
      )}
      <p>{specification.lifecycleState}</p>
      <dl>
        <dt>Generated by</dt>
        <dd>
          {specification.engineName} {specification.engineVersion}
        </dd>
        <dt>Generated at</dt>
        <dd>{specification.generatedAt}</dd>
      </dl>
    </main>
  );
}
