/**
 * T084 — the specification detail view (US3).
 *
 * FR-022: the generating engine and its version are provenance and always
 * shown. FR-032: out-of-date is a state a human acts on — flagged as a live
 * status region, never auto-corrected.
 *
 * EPIC-041 T1376 (`FR-LPW-044`, `R-041-11`): `LifecycleControls`,
 * `ValidationFindings`, `VersionHistory` and `VersionDiff` were built and
 * tested in EPIC-005 and mounted nowhere. They are mounted here, each keeping
 * its own four states; a transition refreshes the specification; a diff opens
 * from two selections in the history.
 */
import { useCallback, useEffect, useState, type ReactElement } from 'react';
import { ApiError, type ApiClient, type Specification } from '../services/api';
import { LifecycleControls } from '../components/LifecycleControls';
import { ValidationFindings } from '../components/ValidationFindings';
import { VersionDiff } from '../components/VersionDiff';
import { VersionHistory } from '../components/VersionHistory';
import { MarkdownViewer } from '../design/components/MarkdownViewer';

export interface SpecificationViewProps {
  api: ApiClient;
  specificationId: string;
}

export function SpecificationView({ api, specificationId }: SpecificationViewProps): ReactElement {
  const [specification, setSpecification] = useState<Specification | null>(null);
  const [error, setError] = useState<string | null>(null);
  // Two selections from the history make a diff; a third starts over.
  const [selected, setSelected] = useState<number[]>([]);

  const load = useCallback(async (): Promise<void> => {
    try {
      setSpecification(await api.getSpecification(specificationId));
    } catch (err) {
      setError(err instanceof ApiError ? err.message : 'Something went wrong. Please try again.');
    }
  }, [api, specificationId]);

  useEffect(() => {
    void load();
  }, [load]);

  if (specification === null) {
    return <main>{error !== null ? <p role="alert">{error}</p> : <p>Loading…</p>}</main>;
  }

  // EPIC-020 T268 (SC-ENH-006): ONE live region for staleness. FR-032's
  // out-of-date flag and FR-ENH-006's currency status share it, so the two
  // can never disagree on screen — and no specification is silently stale.
  const stale = specification.isOutOfDate || specification.currencyStatus === 'stale';
  const staleDetail =
    specification.staleReason ?? 'its source requirements changed after generation';

  const select = (versionNumber: number): void => {
    setSelected((current) => (current.length >= 2 ? [versionNumber] : [...current, versionNumber]));
  };
  const [from, to] = selected.length === 2 ? [...selected].sort((a, b) => a - b) : [undefined, undefined];

  return (
    <main>
      <h1>{specification.title}</h1>
      {stale && (
        <p role="status">
          This specification is not current (out of date) — {staleDetail}. Nothing is regenerated
          automatically; reconcile it deliberately.
        </p>
      )}
      <p>{specification.lifecycleState}</p>
      <dl>
        <dt>Generated by</dt>
        <dd>
          {specification.engineName} {specification.engineVersion}
        </dd>
        <dt>Generated at</dt>
        <dd>{specification.generatedAt}</dd>
      </dl>
      {specification.sourcePath != null && (
        <p className="ds-field__hint">
          Synced from <code>{specification.sourcePath}</code>
          {specification.currentVersion ? ` by execution ${specification.currentVersion.authoredById}` : ''} — the project directory is authoritative.
        </p>
      )}
      {/* EPIC-045 T1661 (FR-ART-019): the SAME renderer the Epic detail uses, so
          there is exactly one rendering of untrusted markdown to keep safe. */}
      {specification.currentVersion != null && (
        <section aria-label="Specification content">
          <MarkdownViewer
            markdown={specification.currentVersion.contentRaw}
            sizeBytes={new TextEncoder().encode(specification.currentVersion.contentRaw).length}
            {...(specification.sourcePath != null ? { path: specification.sourcePath } : {})}
          />
        </section>
      )}
      <LifecycleControls
        api={api}
        specificationId={specificationId}
        lifecycleState={specification.lifecycleState}
        onTransitioned={() => void load()}
      />
      <ValidationFindings api={api} specificationId={specificationId} />
      <VersionHistory api={api} specificationId={specificationId} onSelect={select} />
      {from !== undefined && to !== undefined && from !== to && (
        <VersionDiff api={api} specificationId={specificationId} fromVersion={from} toVersion={to} />
      )}
    </main>
  );
}
