/**
 * `T1477` (EPIC-042, `FR-EXT-020`, `R-042-4`) — the invariant Governed Execution
 * text and the generated-file header live in the bundle, not in `backend/src`.
 *
 * The text necessarily names the toolkit's command prefix, which `backend/src`
 * may not contain (`engine-independence.spec.ts`); the backend imports a
 * function and never the words. Written to FAIL before `T1478`.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { constitutionDir, constitutionHeader, governedExecutionSection } from '../src/index.js';

const INVARIANT = readFileSync(join(constitutionDir(), 'governed-execution.md'), 'utf8').replace(/\r\n/g, '\n');

describe('T1477 · governedExecutionSection', () => {
  it('starts with the machine-readable offline-mode line, then the invariant text byte-for-byte', () => {
    const strict = governedExecutionSection('strict');
    expect(strict.startsWith('Offline mode: strict\n\n')).toBe(true);
    expect(strict.slice('Offline mode: strict\n\n'.length)).toBe(INVARIANT);
    const provisional = governedExecutionSection('provisional');
    expect(provisional.startsWith('Offline mode: provisional\n\n')).toBe(true);
    expect(provisional.slice('Offline mode: provisional\n\n'.length)).toBe(INVARIANT);
  });

  it('carries Constitution XII intent: register before, complete after, never the database, never self-approve, stop when unreachable', () => {
    for (const phrase of ['registered with PMI Studio before it starts', 'completed after it ends', 'Never write to PMI Studio', 'Never approve your own', 'unreachable', 'not governed']) {
      expect(INVARIANT).toContain(phrase);
    }
  });

  it('is invariant: the file ends with exactly one newline and contains no placeholder', () => {
    expect(INVARIANT.endsWith('\n')).toBe(true);
    expect(INVARIANT.endsWith('\n\n')).toBe(false);
    expect(INVARIANT).not.toMatch(/\[[A-Z_]+\]|<[a-z]+>/);
  });
});

describe('T1477 · constitutionHeader', () => {
  it('renders the generated-file header naming project, version and digest, and where to change it', () => {
    const header = constitutionHeader({ projectId: 'p_1', version: 3, digest: 'a'.repeat(64) });
    expect(header.startsWith('<!-- GENERATED by PMI Studio from project p_1 · constitution version 3 · digest ' + 'a'.repeat(64))).toBe(true);
    expect(header).toContain('Do not edit here');
    expect(header).toContain('Governance → Constraints');
    expect(header).toContain('/setup-PMIStudio');
    expect(header.endsWith('-->\n')).toBe(true);
  });

  it('is deterministic', () => {
    const a = constitutionHeader({ projectId: 'p', version: 1, digest: '0'.repeat(64) });
    const b = constitutionHeader({ projectId: 'p', version: 1, digest: '0'.repeat(64) });
    expect(a).toBe(b);
  });
});
